# Generated by Django 3.2.4 on 2021-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
